---
title: "R Notebook"
output: html_notebook
---


```{r}
library(readr)
library(ggplot2)
cars <- read_csv("cars_sample.csv")

cars_scatterplot = ggplot(cars, aes(x=Weight, y=MPG)) +
  geom_point(aes(size=Weight, color=Manufacturer, alpha=.5)) + 
  labs(title="Cars Weight vs MPG", x='Weight (lbs)')
cars_scatterplot
```

```{r}
library(plotly)
p <- plot_ly(cars, x = ~Weight, y = ~MPG, color = ~Manufacturer, size=~Weight, alpha=.5)
p
```

```{r}
library(shiny)
library(ggplot2)
library(plotly)

ui <- fluidPage(
  headerPanel('Data Vis Project'),
  sidebarPanel(
    varSelectInput(
      inputId = "x",
      label = "X axis Variable",
      data = cars,
      selected = 'Weight'
    ),
    varSelectInput(
      inputId = "y",
      label = "Y axis Variable",
      data = cars,
      selected = "MPG"
    ),
    varSelectInput(
      inputId = "w",
      label = "Point Size Variable",
      data = cars,
      selected = "Weight"
    )
  ),
  mainPanel(
  # numericInput(inputId = 'a',
  #              label = "Input an alpha value (opacity) between 0 and 1:",
  #              value = .5),
  plotlyOutput(outputId = "chart")
  )
)

server <- function(input, output) {
  output$chart <- renderPlotly({
    colx <- sym(input$x)
    coly <- sym(input$y)
    colw <- sym(input$w)
    # cola <- num(/input$a)
    p <-
      ggplot(cars,
             aes(
               x = !!colx,
               y = !!coly,
               size = !!colw,
               color = Manufacturer,
               alpha = .5
             )) +
      geom_point() +
      labs(title = "Cars Scatterplot")
    ggplotly(p)
  })
}

shinyApp(ui,server)

```
